// Supabase配置
const SUPABASE_URL = 'https://xujmkwdenbsuyfgkdtgd.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1am1rd2RlbmJzdXlmZ2tkdGdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NjEzMTEsImV4cCI6MjA2OTQzNzMxMX0.wxdUMOEUDieks9j_PM3K-I6MRWMzoZGLTpl8oznbUuY';
